# Generated by Django 4.2.27 on 2026-01-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryattempt',
            new_name='leads_deliv_lead_id_a96057_idx',
            old_name='leads_deliv_lead_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundlead',
            new_name='leads_inbou_status_c37de5_idx',
            old_name='leads_inbou_status_a1b2c3_idx',
        ),
    ]
